/* THIS FILE IS AUTO-GENERATED BY STEFF-ENGINE. PLEASE DO NOT MODIFY. */

#pragma once
namespace SteffEngine
{
	namespace Editor
	{
		inline const size_t componentNamesSize{ 9 };

		inline const char* componentNames[]
		{
			"CameraComponent\0",
			"CharacterControllerComponent\0",
			"InstancedMeshRendererComponent\0",
			"MeshRendererComponent\0",
			"RigidBodyComponent\0",
			"BoxColliderComponent\0",
			"CapsuleColliderComponent\0",
			"PlaneColliderComponent\0",
			"SphereColliderComponent\0",
		};

		inline size_t GetComponentNamesSize()
		{
			return componentNamesSize;
		}

		inline const char** GetComponentNames()
		{
			return componentNames;
		}
	}
}
