/* THIS FILE IS AUTO-GENERATED BY STEFF-ENGINE. PLEASE DO NOT MODIFY. */

#pragma once
#include "pch.h"

#include "ScriptComponentExposing.h"
#include "ScriptComponentNamesStruct.h"
#include "ScriptManager.h"

#include "WaterSplashComponent.h"

using namespace SteffEngine::Core;
using namespace SteffEngine::Editor;

// BEGIN CLASS WaterSplashComponent.h - WaterSplashComponent
std::vector<ExposedVariableData> SteffEngine::Core::Components::WaterSplashComponent::GetEditorData() const
{
	std::vector<ExposedVariableData> data{ 0 };


	return data;
}
// END CLASS

ENGINE_API
SteffEngine::Core::Components::Component* CreateComponent(size_t hash, SteffEngine::Core::GameObject* pGameObject)
{
	if(SteffEngine::Core::Components::WaterSplashComponent::GetHash() == hash) return pGameObject->CreateComponent<SteffEngine::Core::Components::WaterSplashComponent>();

	return nullptr;
}

ENGINE_API
String GetComponentName(SteffEngine::Core::Components::Component* pComponent)
{
	if(pComponent->IsSameType<SteffEngine::Core::Components::WaterSplashComponent>()) return SteffEngine::Core::Components::WaterSplashComponent::GetName();

	return nullptr;
}

ENGINE_API
ScriptComponentNamesStruct GetComponentNames()
{
	return ScriptComponentNamesStruct{ SteffEngine::Editor::GetComponentNamesSize(), SteffEngine::Editor::GetComponentNames() };
}
