/* THIS FILE IS AUTO-GENERATED BY STEFF-ENGINE. PLEASE DO NOT MODIFY. */

#pragma once
namespace SteffEngine
{
	namespace Editor
	{
		inline const size_t componentNamesSize{ 0 };

		inline const char** componentNames{ nullptr };

		inline size_t GetComponentNamesSize()
		{
			return componentNamesSize;
		}

		inline const char** GetComponentNames()
		{
			return componentNames;
		}
	}
}
